# -*- coding: utf-8 -*-
"""Test Case Cashier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pAVJnVmM3nz_8bzkmUoDw57Kp0E8XA-
"""

import pandas as pd
import cashier as c

test_case = c.Transaction()

test_case.add_item("Ayam Goreng", 2, 20000)
test_case.add_item("Pasta Gigi", 3, 15000)
test_case.show_order()

test_case.delete_item("Pasta Gigi")
test_case.show_order()

test_case.reset_item()

test_case.add_item("Ayam Goreng", 2, 20000)
test_case.add_item("Pasta Gigi", 3, 15000)
test_case.add_item("Mainan Mobil", 1, 200000)
test_case.add_item("Mi Instan", 5, 3000)
test_case.show_order()
test_case.total_price()

